CREATE TABLE IF NOT EXISTS status (
    id VARCHAR(32) PRIMARY KEY,
    status VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS task (
    id VARCHAR(32) PRIMARY KEY,
    description VARCHAR(1024),
    status_id VARCHAR(32),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (status_id) REFERENCES status(id)
);