CREATE TABLE IF NOT EXISTS task (
    id VARCHAR(36) PRIMARY KEY,
    title VARCHAR(64),
    description VARCHAR(1024),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);